### ISSUE TITLE
LUT: 0->Black BWR

### ISSUE THREAD

**Issue by tischi** [embl-cba/fiji-plugin-platyBrowser#20]
@vzinche
I thought of creating a new LUT, in which plain zeros are black, i.e. are not shown at all. 
I thought this should be useful for the MEDs coloring, because all those blue cells are visually very distracting. What do you think?

**Comment by vzinche** [comment]
Hmm, I guess I wouldn't agree, because it's easier to spot a red cell on a blue background, rather than in the raw em data. 

I don't know, maybe we can ask other guys during the PlatyMeeting 
On Thu, Apr 18, 2019 at 14:37, tischi  wrote: @vzinche (https://github.com/vzinche)
 I thought of creating a new LUT, in which plain zeros are black, i.e. are not shown at all.
 I thought this should be useful for the MEDs coloring, because all those blue cells are visually very distracting. What do you think?

**Comment by tischi** [comment]
But my point is that it is now very hard to identify cells with low expression, because they are blue islands in a vast blue ocean of non expressing ones....

**Comment by vzinche** [comment]
Okay, a valid point. In this case it's better to have both schemes to choose from!
On Thu, Apr 18, 2019 at 15:23, tischi  wrote: But my point is that it is now very hard to identify cells with low expression, because they are blue islands in a vast blue ocean of non expressing ones....
